### ISSUE TITLE
not available on RubyGems?

### ISSUE THREAD

**Issue by mooreniemi** [pry/pry-bond#10]
`bash: gem install pry-bond`
`ERROR:  Could not find a valid gem 'pry-bond' (>= 0) in any repository`
`ERROR:  Possible alternatives: pry-bot`

**Comment by kaibioinfo** [comment]
I think the reason it was not available on rubygems was that it just runs with the pre-release version of pry. But this has changed now, so I pushed it on rubygems (I tested the gem on linux on jruby and ruby 2.15. I still have to test it on Windows and Rubinius).
I don't know the policy of publishing gems on github, so I hope it is okay that I did this.
