### ISSUE TITLE
add rb-readline dependency.

### ISSUE THREAD

**Issue by ghost** [pry/pry-bond#2]
rb-readline might be a failsafe solution to work on all different platforms/scenarios (windows, jruby, OSX, etc). 
also mentioned in https://github.com/cldwalker/bond 
could make sure pry-bond works everywhere.

**Comment by ghost** [comment]
ping @yui-knk since you seem to be interested in bond as well.

**Comment by yui-knk** [comment]
I think it is good to add dependency. Because bond mentions to do so is good :)
