### ISSUE TITLE
Unable to install pry-bond - no valid gem?

### ISSUE THREAD

**Issue by simonweil** [pry/pry-bond#8]
```
$ gem install pry-bond
ERROR:  Could not find a valid gem 'pry-bond' (>= 0) in any repository
```

Please help...

**Comment by ghost** [comment]
it hasn't been released as a gem yet. 
you can try this:

```
git clone git@github.com:pry/pry-bond.git
cd pry-bond
gem build pry-bond.gemspec
gem install pry-bond-*.gem
```

i haven't used this gem myself a lot.

**Comment by kaibioinfo** [comment]
Am 25.04.2014 10:21, schrieb Simon Weil:

> |$ gem install pry-bond
> ERROR:  Could not find a valid gem 'pry-bond' (>= 0) in any repository
> |
> 
> Please help...
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/pry/pry-bond/issues/8.
> 
> Important: pry-bond can only be used with the newest (unreleased) pry 
> version. So you have to install pry from github, too.

|git clone git@github.com:pry/pry.git
cd pry
gem build pry.gemspec
gem install pry*.gem|

For the stable pry version there is no need to install pry-bond as bond 
is already integrated.

**Comment by simonweil** [comment]
OK, thank you.
